version: 2.1

jobs:
    build:
        docker:
            - image: circleci/golang:1
        environment:
            GOLANGCI_LINT_VER: 1.17.1
        steps:
            - checkout
            - run:
                name: Initialize
                command: |
                    rmdir /go/*/ # fix owner/permission
                    env | grep _VER | sort > /tmp/tools.ver
            - restore_cache:
                keys:
                    - v1-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-{{ .Branch }}
                    - v1-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-
                    - v1-{{ checksum "/tmp/tools.ver" }}-
                    - v1-
            - run:
                name: Install tools
                command: |
                    cd /
                    golangci-lint --version | tee /dev/stderr | grep -wq $GOLANGCI_LINT_VER ||
                        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b /go/bin v$GOLANGCI_LINT_VER
                    go get -v github.com/mattn/goveralls
            - run: go test -mod=readonly -v -race ./...
            - run: golangci-lint run
            - run: goveralls -service=circle-ci
            - save_cache:
                when: always
                key: v1-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-{{ .Branch }}
                paths:
                    - /go/bin/
                    - /go/pkg/
                    - /go/src/
                    - ~/.cache/go-build/
